# Site
#repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Personal info
name: Pia Benaud    
title: Postdoctoral Research Associate
email: P.Benaud@exeter.ac.uk
website: http://geography.exeter.ac.uk/staff/index.php?web_id=Pia_Benaud

# Social links
twitter_username: piabenaud
github_username:  piabenaud
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 This is very much a work in progess

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  To come

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
